language: c

dist: xenial

matrix:
  include:
    - os: linux
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-gcc"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"

    - os: linux
      env:
        - "C_COMPILER=clang-6.0"
        - "CXX_COMPILER=clang++-6.0"
        - "SIZE=llvm-size-6.0"
        - "OBJCOPY=llvm-objcopy-6.0"
        - "LINKER=lld-6.0"
        - "LLD=ld.lld-6.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - llvm-6.0
            - lld-6.0

    - os: linux
      env:
        - "C_COMPILER=clang-7"
        - "CXX_COMPILER=clang++-7"
        - "SIZE=llvm-size-7"
        - "OBJCOPY=llvm-objcopy-7"
        - "LINKER=lld-7"
        - "LLD=ld.lld-7"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - llvm-7
            - lld-7

    - os: linux
      env:
        - "C_COMPILER=clang-8"
        - "CXX_COMPILER=clang++-8"
        - "SIZE=llvm-size-8"
        - "OBJCOPY=llvm-objcopy-8"
        - "LINKER=lld-8"
        - "LLD=ld.lld-8"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - llvm-8
            - lld-8

script:
  - sh ci/script.sh