language: c

dist: xenial

matrix:
  include:
    - os: linux
      env:
        - "C_COMPILER=clang-6.0"
        - "CXX_COMPILER=clang++-6.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - llvm-6.0
            - lld-6
  allow_failures:
    - os: linux
      env:
        - "C_COMPILER=clang-6.0"
        - "CXX_COMPILER=clang++-6.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - llvm-6.0
            - lld-6

script:
  - $C_COMPILER --version
  - $CXX_COMPILER --version
  - which llvm-objdump
  - which llvm-objdump-6.0
  - which llvm-size
  - which llvm-size-6.0